### ISSUE TITLE
Prediction input table shouldn't be required to have LABEL column

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#846] opened 2019-09-18 07:31 UTC
If the feature name of the dataset contains uppercase letters, an error will be reported when the model is predicted like as follows:

```python
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "loadModelMeta verifyColumnNameAndType: predFields doesn't contain column Pclass_1"
	debug_error_string = "{"created":"@1568788153.690183400","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"loadModelMeta verifyColumnNameAndType: predFields doesn't contain column Pclass_1","grpc_status":2}"
>
```

**Comment by Echo9573** [comment] 2019-09-18 07:39
The complete running process is shown as follows:
![image](https://user-images.githubusercontent.com/24820352/65127543-35f15200-da2a-11e9-98c2-02941e53ac61.png)
![image](https://user-images.githubusercontent.com/24820352/65127755-ab5d2280-da2a-11e9-973a-f697838a4825.png)

**Comment by tonyyang-svail** [comment] 2019-09-26 23:32
The cause is the prediction job requires input table having the `LABEL` column. We should release this restriction.

**Comment by Echo9573** [comment] 2019-10-17 10:03
Excuse me, I have tested the latest image and found that the problem still exists. How is the problem progressing? @tonyyang-svail

**Comment by tonyyang-svail** [comment] 2019-10-17 17:06
Hi @Echo9573, the SQLFlow team is planning to fix it in next week. Sorry for the inconvenience.

**Comment by tonyyang-svail** [comment] 2019-10-17 19:00
Also notifying @weiguoz @typhoonzero @Yancey1989, please be aware of this issue when migrating to the `PredictIR`.

**Comment by typhoonzero** [comment] 2020-09-15 02:54
We don't need the label column to be present when predicting in the latest SQLFlow, closing.

**Closed as completed by typhoonzero** 2020-09-15 02:54 UTC
Labels: bug, PRI/P1, DiDi, DataScience
