### ISSUE TITLE
cannot import name 'create_prompt_application'

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#1284] opened 2019-12-01 14:33 UTC
**Description**
When issuing `EXPLAIN` clause
```sql
%%sqlflow
SELECT * FROM notebook_dev.iris_train
TO EXPLAIN notebook_dev.iris_xgb_model
WITH
    shap_summary.plot_type="dot",
    shap_summary.alpha=1,
    shap_summary.sort=True
USING TreeExplainer; 
```
it will throw exception as following and it will cause serious problem that the kernel will be shutdown and can not be restarted.

```bash
debug_error_string = "{"created":"@1575011880.509916780","description":"Error received from peer ipv4:10.82.128.7:8005","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"failed: exit status 1
==========Program==========
import xgboost
import shap
import json
import matplotlib.pyplot as plt
import pandas as pd
from sqlflow_submitter.db import connect_with_data_source, db_generator
shap.initjs()
feature_field_meta = json.loads('''[{"name":"sepal_length","dtype":1,"delimiter":"","shape":[1],"is_sparse":false,"vocabulary":null,"MaxID":0},{"name":"sepal_width","dtype":1,"delimiter":"","shape":[1],"is_sparse":false,"vocabulary":null,"MaxID":0},{"name":"petal_length","dtype":1,"delimiter":"","shape":[1],"is_sparse":false,"vocabulary":null,"MaxID":0},{"name":"petal_width","dtype":1,"delimiter":"","shape":[1],"is_sparse":false,"vocabulary":null,"MaxID":0}]''')
feature_column_name = sorted([k["name"] for k in feature_field_meta])
feature_spec = {k['name']: k for k in feature_field_meta}
conn = connect_with_data_source('''hive://USER:PASSWORD@IP:PORT/DEFAULT_DB?auth=PLAIN&session.mapreduce.job.queuename=root.jichupingtaibu_tenant_dev&session.hive.exec.compress.intermediate=true&session.hive.auto.convert.join=true&session.hive.exec.parallel=true''')
label_name = "class"
summaryAttrs = json.loads('''{}''')
def analyzer_dataset():
    stream = db_generator(conn.driver, conn, """
    SELECT * FROM notebook_dev.iris_train
""", feature_column_name, label_name, feature_spec)
    xs = pd.DataFrame(columns=feature_column_name)
    ys = pd.DataFrame(columns=[label_name])
    i = 0
    for row in stream():
        xs.loc[i] = row[0]
        ys.loc[i] = row[1]
        i += 1
    return xs, ys
    X,y = analyzer_dataset()
bst = xgboost.Booster()
bst.load_model("my_model")
explainer = shap.TreeExplainer(bst)
shap_values = explainer.shap_values(X)
shap.summary_plot(shap_values, X, show=False, **summaryAttrs)
plt.savefig('summary', bbox_inches='tight')
==========Output==========
/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
  Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/shap/__init__.py", line 15, in <module>
    from .plots.force import force_plot, initjs, save_html
  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/shap/plots/force.py", line 11, in <module>
    from IPython import get_ipython
  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 22, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
    ImportError: cannot import name 'create_prompt_application'
","grpc_status":2}"
```

**Reproduction Steps**
Normal `Explain` clause in environment with `prompt-toolkit==2.0.10`

**Expected Behavior**
Correct output  image of `SHAP`.

**Screenshots**
 
 
![WX20191201-221224](https://user-images.githubusercontent.com/4661989/69915506-b7ce1480-148a-11ea-9227-26f3cc766f64.png)

 

**Additional Notes**
The solution for this problem is to install `prompt-toolkit==1.0.15` instead of `2.0.10` since the `IPython` module depends on this version.

Other links may be helpful.
[Jupyter ImportError: cannot import name 'create_prompt_application' ubuntu 18.04](https://stackoverflow.com/questions/55243773/jupyter-importerror-cannot-import-name-create-prompt-application-ubuntu-18-04)

[How can I use JupyterLab with allennlp==0.3.0?](https://stackoverflow.com/questions/52956944/how-can-i-use-jupyterlab-with-allennlp-0-3-0)

[ipython - "cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts'](https://stackoverflow.com/questions/51676835/ipython-cannot-import-name-create-prompt-application-from-prompt-toolkit-s)

[Fresh Jupyter Install fails on notebook launch - "ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts'](https://superuser.com/questions/1457202/fresh-jupyter-install-fails-on-notebook-launch-importerror-cannot-import-nam)

However I am not sure whether other modules require `prompt-toolkit==2.0.10` strongly. But this solution seems work for me.

**Comment by tonyyang-svail** [comment] 2019-12-04 04:26
@BlackPoint-CX Thanks for submitting this issue. To fix this issue, do we need to update the pysqlflow dependency?

**Comment by tonyyang-svail** [comment] 2019-12-09 02:16
I am closing this issue since we are unable to reproduce this behavior in our Docker image. We suspect this issue may appear in native build. Thank @BlackPoint-CX for filing it.

**Closed as completed** 2019-12-09 02:18 UTC
Labels: DiDi, DataScience
