### ISSUE TITLE
Potential issue when running tests concurrently

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/sqlflow#1037] opened 2019-10-18 14:02 UTC
Currently `main_test.go` runs end2end tests by first populating the data to database. This would normally work well for local DB inside docker container. However, for tests related to ODPS/Maxcompute, we are using a real database using SQL in `iris_sql.go` which looks like the following:
```
DROP TABLE IF EXISTS gomaxcompute_driver_w7u.sqlflow_test_iris_train;
CREATE TABLE gomaxcompute_driver_w7u.sqlflow_test_iris_train
...
```
Since the table name is fixed, if the multiple test runs are executed concurrently, there's a chance that either the table is being dropped or being created, which might fail other test runs that rely on this particular table. I've seen this happen several times when developing locally or testing on Travis CI.

**Comment by tonyyang-svail** [comment] 2019-10-18 17:03
Hi @terrytangyuan, thanks for mentioning this issue. Would you mind posting the reference build log?

Also, I am wondering which two test cases have the race condition. Since all test scripts are running sequentially, and all go tests are running sequentially with the `-p 1` flag. I don't think there is a race condition within a CI run.

However, there is indeed a race condition between two CI runs.

**Comment by terrytangyuan** [comment] 2019-10-18 17:08
@tonyyang-svail Sorry for the confusion. By "multiple test runs", I actually meant among multiple CI runs instead of multiple test cases.

One example build log can be found [here](https://travis-ci.com/sql-machine-learning/sqlflow/builds/132491314#L4067-L4071), specifically the following error log is relevant:
```
=== RUN   TestEnd2EndMaxComputeElasticDL
--- FAIL: TestEnd2EndMaxComputeElasticDL (69.11s)
    main_test.go:429: prepare test dataset failed: Get https://service.cn.maxcompute.aliyun.com/api/projects/gomaxcompute_driver_w7u/instances/20191018110402240g6im26pr2?result=: dial tcp 139.196.65.93:443: i/o timeout
FAIL
FAIL	sqlflow.org/sqlflow/cmd/sqlflowserver	69.127s
```

**Comment by wangkuiyi** [comment] 2019-12-10 19:45
Thanks to @terrytangyuan for the finding.

@tonyyang-svail Can we remove the `-p 1` from the `go test` command-line?  I feel that it's requiring running tests sequentially might imply a bad design which might cause us other troubles in the future.

If needed, we could extract `iris_sql.go` out from its current directory location into a binary program, say, `fill_in_data`.  And make the CI calls this binary before running tests.

**Comment by typhoonzero** [comment] 2019-12-11 02:05
Thanks @terrytangyuan, I think we really need to ensure that all tests can run concurrently, and each test can run multiple times on the local machine. Yet, the error `    main_test.go:429: prepare test dataset failed: Get https://service.cn.maxcompute.aliyun.com/api/projects/gomaxcompute_driver_w7u/instances/20191018110402240g6im26pr2?result=: dial tcp 139.196.65.93:443: i/o timeout
` seems caused by network issue.

**Comment by tonyyang-svail** [comment] 2019-12-11 02:20
@wangkuiyi Many test cases are saving the model into the same table, for example `SELECT ... TO TRAIN ... INTO same_table` appears multiple times in `pkg/sql` and `cmd/server`. To avoid the race condition, I added `-p 1`.

**Comment by wangkuiyi** [comment] 2019-12-11 04:05
It seems that the right way is that each unit test saves its model into a unique table, say `test-name-<random_number>`. Is it? @tonyyang-svail

**Comment by tonyyang-svail** [comment] 2019-12-11 05:54
Right. 👍

**Comment by typhoonzero** [comment] 2020-09-15 05:41
This is fixed in the latest SQLFlow.

**Closed as completed by typhoonzero** 2020-09-15 05:41 UTC
